---
title: "Account Payments Classification: Naive Bayes, SVM"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(tidytext)

# Display sheets of interest in the Excel document
excel_sheets("kv_20_ucty.xlsx")

```

# Extracting relevant sheets for machine learning algoritm + preprocessing

```{r}
# For the machine learning task, we only extract columns of interest

ano <- read_excel("kv_20_ucty.xlsx", sheet = 3, skip = 4,
                  col_names = c("index",
                                "datum",
                                "castka",
                                "protiucet",
                                "zprava_1",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod",
                                "extra_1",
                                "extra_2")) %>% 
        transmute(zprava = zprava_1, typ = as.factor(typ)) %>%  
        mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

pirati <- read_excel("kv_20_ucty.xlsx", sheet = 4, skip = 4,
                  col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "zprava_2",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod",
                                "extra_1",
                                "extra_2")) %>% 
          transmute(zprava = paste(zprava_1, zprava_2),
                    typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

cssd <- read_excel("kv_20_ucty.xlsx", sheet = 5, skip = 4,
                   col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "zprava_2",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod",
                                "extra_1",
                                "extra_2",
                                "extra_3")) %>% 
          transmute(zprava = paste(zprava_1, zprava_2), typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

kdu_csl <- read_excel("kv_20_ucty.xlsx", sheet = 6, skip = 4,
                   col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "zprava_2",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod",
                                "extra_1",
                                "extra_2",
                                "extra_3")) %>% 
          transmute(zprava = paste(zprava_1, zprava_2), typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

kscm <- read_excel("kv_20_ucty.xlsx", sheet = 7, skip = 4,
                   col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "zprava_2",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod",
                                "extra_1",
                                "extra_2")) %>% 
          transmute(zprava = paste(zprava_1, zprava_2), typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

ods <- read_excel("kv_20_ucty.xlsx", sheet = 8, skip = 4,
                   col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "zprava_2",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod",
                                "extra_1",
                                "extra_2")) %>% 
          transmute(zprava = paste(zprava_1, zprava_2), typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))
  
stan <- read_excel("kv_20_ucty.xlsx", sheet = 9, skip = 4,
                   col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "zprava_2",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod")) %>% 
          transmute(zprava = paste(zprava_1, zprava_2), typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))
  
spd <- read_excel("kv_20_ucty.xlsx", sheet = 10, skip = 4,
                   col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "zprava_2",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod")) %>% 
          transmute(zprava = paste(zprava_1, zprava_2), typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))
  
top09 <- read_excel("kv_20_ucty.xlsx", sheet = 11, skip = 4,
                   col_names = c("index",
                                "datum",
                                "castka",
                                "protiucet",
                                "zprava_1",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod",
                                "extra_1")) %>% 
          transmute(zprava = zprava_1, typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))
  
trikolora <- read_excel("kv_20_ucty.xlsx", sheet = 12, skip = 4,
                   col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "extra_1",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod")) %>% 
          transmute(zprava = zprava_1, typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

ods_top09 <- read_excel("kv_20_ucty.xlsx", sheet = 21, skip = 4,
                    col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod")) %>% 
          transmute(zprava = zprava_1, typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

sck_spojenci <- read_excel("kv_20_ucty.xlsx", sheet = 28, skip = 4,
                    col_names = c("index",
                                "datum",
                                "castka",
                                "protiucet",
                                "zprava_1",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod")) %>% 
          transmute(zprava = zprava_1, typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))


olo_kdu_top_zel <- read_excel("kv_20_ucty.xlsx", sheet = 29, skip = 4,
                    col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod"),
                    n_max = 108) %>% 
          transmute(zprava = zprava_1, typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

lbk_kdu_top <- read_excel("kv_20_ucty.xlsx", sheet = 30, skip = 4,
                    col_names = c("index",
                                "datum",
                                "castka",
                                "protiucet",
                                "zprava_1",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod",
                                "extra_1")) %>% 
          transmute(zprava = zprava_1, typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

khk_cssd_zel <- read_excel("kv_20_ucty.xlsx", sheet = 31, skip = 4,
                    col_names = c("index",
                                "datum",
                                "castka",
                                "zprava_1",
                                "typ",
                                "typ_dlouhy",
                                "strana_koalice",
                                "subjekt",
                                "kod")) %>% 
          transmute(zprava = zprava_1, typ = as.factor(typ)) %>%  
          mutate(firma = str_extract(string = zprava, pattern = "(?<=ICO|ico|ico.|ICO.)[0-9]{8}"))

```


# Binding all datasets to one, further processing

```{r}
# For this dataset, we also exclude the extracted company information and lowercase

ml_dataset <- bind_rows(ano, pirati, cssd, kdu_csl, kscm, ods, stan, spd, top09, trikolora, ods_top09, sck_spojenci, olo_kdu_top_zel, lbk_kdu_top, khk_cssd_zel) %>% 
              select(-firma) %>% 
              mutate(zprava = str_to_lower(zprava))
  
# How many factor levels of "typ" we have?
ml_dataset  %>% 
  group_by(typ) %>% 
  count() %>% 
  arrange(desc(n))
  
# One category is accidentally capitalized...
ml_dataset  %>%
  filter(typ == "O")

#...so we merge it with the noncapitalized category, together with g category
# We also eliminate the "error" category because of low amount of information

ml_dataset <- ml_dataset %>% 
  filter(typ != "e") %>% 
  mutate(typ = fct_collapse(typ, "o" = "O", "d" = "g") %>% fct_drop())

# How many factor levels of "typ" we have now?
ml_dataset  %>% 
  group_by(typ) %>% 
  count() %>% 
  arrange(desc(n))


```

# Converting text to a machine-readable format for ML model

```{r}

library(udpipe)
udpipe_test <- ml_dataset %>% 
               rename(text = zprava, doc_id = typ) %>% 
               udpipe(object = "czech-pdt")


ml_tokens <- ml_dataset %>%
  unnest_tokens(output = "word", token = "words", input = zprava) 

testik <- ml_tokens %>%
  count(typ, word)



# Create a document term matrix using TFIDF weighting
ml_matrix <- ml_tokens %>%
  count(typ, word) %>%
  cast_dtm(document = typ, term = word,
           value = n, weighting = tm::weightTfIdf)

ml_matrix

ml_tidy <- tidy(ml_matrix)

library(randomForest)

# Create train/test split
set.seed(1111)
sample_size <- floor(0.75 * nrow(ml_tidy))
train_ind <- sample(nrow(ml_tidy), size = sample_size)
train <- ml_tidy[train_ind, ]
test <- ml_tidy[-train_ind, ]

# Create a random forest classifier
rfc <- randomForest(data = train, as_factor(document) ~ count,
                    nTree = 50)
# Print the results
rfc

test$document <- as_factor(test$document)
summary(predict(rfc, test))



#############################

ml_tokens_long <- ml_dataset %>%
  unnest_tokens(output = "word", token = "words", input = zprava) %>%
  count(typ, word) %>%
  bind_tf_idf(document = typ, term = word, n = n) %>%
  select(typ, word, tf_idf)

ml_tokens_wide <- ml_tokens_long %>%
  select(typ, word, tf_idf) %>%
  pivot_wider(names_from = word, names_prefix = "word_",
              values_from = tf_idf, values_fill = 0) 

ml_tokens_dfm_sparse <- ml_tokens_long %>%
  cast_dfm(typ, word, tf_idf)

dimnames(ml_tokens_wide) <- list(row_names = ml_tokens_wide[,1], col_names = colnames(ml_tokens_wide))
ml_tokens_wide <- ml_tokens_wide[,-1]

# Find the highest TFIDF values
ml_tokens_long %>%
  arrange(desc(tf_idf))


sample_size <- floor(0.75 * nrow(ml_tokens_long))
train_ind <- sample(nrow(ml_tidy), size = sample_size)



ml_tokens_wide$word_2 <- NULL 
ml_tokens_wide$word_na <- NULL 
ml_tokens_wide$word_reklama <- NULL 


#############################

library(e1071)
library(tm)

svm_model <- svm(x = ml_tokens_wide[,2:ncol(ml_tokens_wide)], y = ml_tokens_wide$typ)


predict(svm_model, ml_tokens_wide[,2:ncol(ml_tokens_wide)])


```





# Work in progress: extraction of companies using regex

```{r}
# Extracting companies

ml_dataset_companies <- ml_dataset %>% 
                        mutate(firma = str_extract(string = zprava, pattern = "(sro|s/.r/.o/.|a/.s/.)"))

# pattern = "w*.w*(sro|s.r.o.|a.s.)"

```

