---
title: "TI Accounts scraping"
author: "Ondrej Pekacek"
date: "8 6 2021"
output: html_document
---

Monitorované subjekty a jejich transparentní účty (https://registrace.udhpsh.cz/seznam/ofzvu/2021ps)

1.  ANO 2011
-   https://www.kb.cz/cs/transparentni-ucty/4090453
-   4090453/0100

2.  Piráti-STAN
-   https://wiki.pirati.cz/ft/start
-   https://ib.fio.cz/ib/transparent?a=2601909155
-   2601909155/2010

3.  ODS, KDU-ČSL, TOP 09
-   https://www.ods.cz/o-nas/financovani
-   https://ib.fio.cz/ib/transparent?a=-48
-   2701915288/2010

4.  SPD
-   https://ib.fio.cz/ib/transparent?a=-49
-   https://www.spd.cz/o-nas/volby-do-poslanecke-snemovny-2021/

5.  ČSSD
-   https://ib.fio.cz/ib/transparent?a=-50
-   https://www.cssd.cz/volby-2016/transparentni-ucet-cssd/transparentni-ucet-cssd/

6.  KSČM
-   https://www.csob.cz/portal/firmy/bezne-ucty/transparentni-ucty/ucet/-/ta/217343303
-   217343303/0300
-   https://www.kscm.cz/cs/nase-strana/financovani-strany

7.  Trikolóra
-   2001915105/2010
-   https://ib.fio.cz/ib/transparent?a=2001915105
-   https://www.volimtrikoloru.cz/archiv/financovani

8.  Strana Zelených
-   https://www.zeleni.cz/transparentni-financovani/
-   https://ib.fio.cz/ib/transparent?a=2801916675
-   2801916675/2010

9.  PŘÍSAHA
-   https://www.prisaha.cz/financovani
-   https://ib.fio.cz/ib/transparent?a=2201968914
-   2201968914/2010



```{r}
library(rvest)
library(tidyverse)
library(jsonlite)
library(httr)
library(data.table)
```

# SCRAPING FIO ÚČTŮ

## Funkce pro scraping FIO
```{r}
# Funkce pro scraping vsech zvolenych uctu
# Argument funkce "parties_accounts_links" akceptuje vektor s odkazy na FIO bankovni ucty
# Argument funkce "parties_names" akceptuje jmena stran - jejich format je volitelny, ale poradi musi byt shodne s "parties_accounts_links"

scrape_fio <- function(parties_accounts_links, parties_names) {
  
  if (!dir.exists(dir_name)) {
    dir.create(dir_name)
  } else {
    print("output directory already exists")  
  }
  
  for (i in 1:length(parties_names)) {
    page <- read_html(parties_accounts_links[i])
    fio_tables <- page %>% html_table(header = TRUE, dec = ",")
    table_transactions <- fio_tables[[2]]
    colnames(table_transactions) <- c("datum",
                                      "castka",
                                      "typ",
                                      "nazev_protiuctu",
                                      "zprava_pro_prijemce",
                                      "ks",
                                      "vs",
                                      "ss",
                                      "poznamka")
    myfile <- paste0(dir_name, "/", parties_names[i], ".csv")
    write_excel_csv(table_transactions, file = myfile)
  }   
}

###############

# Funkce pro scraping vsech zvolenych uctu s cilem ulozeni souhrnu jejich stavu do jedne tabulky

scrape_fio_summary <- function(parties_accounts_links, parties_names) {
  
  summary_list <- list()
  
  if (!dir.exists(dir_name)) {
    dir.create(dir_name)
  } else {
    print("output directory already exists")  
  }
  
  for (i in 1:length(parties_names)) {
    
    page <- read_html(parties_accounts_links[i])
    fio_tables <- page %>% html_table(header = TRUE, dec = ",")
    table_party_summary <- fio_tables[[1]]
    table_party_summary <- table_party_summary %>% slice(1) %>% as.character()
    summary_list[[parties_names[i]]] <- table_party_summary
  }
  
  table_total_summary <- as_tibble(t(as_tibble(summary_list)), rownames = "strana")
  colnames(table_total_summary) <- c("strana",
                                     "stav_leden_2021",
                                     "stav_dnes",
                                     "suma_prijmu",
                                     "suma_vydaju",
                                     "suma_celkem",
                                     "bezny_zustatek")
  myfile <- paste0(dir_name, "/aktualni_stav_vsech_uctu.csv")
  write_excel_csv(table_total_summary, file = myfile)
}

```

## Vstupy pro funkce FIO

```{r}
dir_name <- "test" # Specifikace nazvu slozky, kam budou csv soubory ulozeny

names <- c("pirati_stan", 
           "ods_kdu_top09",
           "spd", 
           "cssd",
           "trikolora",
           "zeleni",
           "prisaha")

links <- c("https://ib.fio.cz/ib/transparent?a=2601909155&f=01.01.2021", 
           "https://ib.fio.cz/ib/transparent?a=-48&f=01.01.2021", 
           "https://ib.fio.cz/ib/transparent?a=-49&f=01.01.2021", 
           "https://ib.fio.cz/ib/transparent?a=-50&f=01.01.2021", 
           "https://ib.fio.cz/ib/transparent?a=2001915105&f=01.01.2021", 
           "https://ib.fio.cz/ib/transparent?a=2801916675&f=01.01.2021", 
           "https://ib.fio.cz/ib/transparent?a=2201968914&f=01.01.2021")

scrape_fio(parties_accounts_links = links, parties_names = names)

scrape_fio_summary(parties_accounts_links = links, parties_names = names)

```


# WORK IN PROGRESS: SCRAPING KB ÚČTŮ

```{r}


page <- read_html("https://www.kb.cz/cs/transparentni-ucty/4090453")

scrape_kb_summary <- as.data.frame(fromJSON("https://www.kb.cz/transparentsapi/balance/4090453"))


link <- "https://www.kb.cz/cs/transparentni-ucty/4090453"
page <- read_html(link)


date <- page %>% html_nodes(".nth-child(2)") %>% html_text()
amount <- page %>% html_nodes(".amount_value") %>% html_text()
type <- page %>% html_nodes(".amount_value+ td") %>% html_text()
message <- page %>% html_nodes(".transparent-account__note") %>% html_text()

pageview_response <- GET("https://www.kb.cz/transparentsapi/transactions/4090453")

pageview_data <- content(pageview_response)

http_error(pageview_response)
http_type(pageview_response)

tabulka <- tibble(pageview_data[[2]])


pageview_response <- GET("https://www.kb.cz/transparentsapi/transactions/4090453", query = list("pageSize=75"))

pageview_data <- content(pageview_response)


# config = list(token = "MZsy5sFESYqU7MawXZgR_w")
post_result <- POST("https://www.kb.cz/transparentsapi/transactions/4090453", body = "api: {
            info: '/transparentsapi/balance/4090453',
            list: '/transparentsapi/transactions/4090453',
            pageSize: 50
        }")


http_error(post_result)

```

# WORK IN PROGRESS: SCRAPING ČSOB ÚČTŮ

```{r}
# Standart scraping - access blocked
page <- read_html("https://www.csob.cz/portal/firmy/bezne-ucty/transparentni-ucty/ucet/-/ta/217343303")

download.file("https://www.csob.cz/portal/firmy/bezne-ucty/transparentni-ucty/ucet/-/ta/217343303", "csob.html")


# CSOB Using Selenium
remDr <- remoteDriver(
  remoteServerAddr = "localhost",
  port = 4445L,
  browserName = "firefox"
)

remDr$open()
remDr$getStatus()
remDr$copy()
remDr$getAllCookies()
remDr$deleteAllCookies()
remDr$server$stop()
remDr$quit()

remDr$getCurrentUrl()

remDr$navigate("https://www.csob.cz/portal/firmy/bezne-ucty/transparentni-ucty/ucet/-/ta/217343303")
webElem <- remDr$findElement(using = "name", "dateFilter")  

remDr$navigate("https://www.csob.cz/portal/firmy/bezne-ucty/transparentni-ucty/ucet/-/ta/217343303")

webElem <- remDr$findElement(using = "name", "dateFilter")  

webElem$clickElement()

webElem$sendKeysToElement(list("\uE007"))

webElem <- remDr$findElement(using = "css", ".pdp-pagination-next a")  

```

```{r}
########## CODE SNIPPETS - WORK IN PROGRESS ####################################


# # USING A FOR LOOP FOR KB with a defined end

new_df <- tibble()
full_list <- list()
account_id <- "1153902720297"

for (i in seq.int(from = 0, to = 50, by = 50)) {
  
full_list[[as.character(i)]] <- fromJSON(content(GET(url = paste0("https://www.kb.cz/transparentsapi/transactions/", account_id, "?skip=", i)), as = "text"))[[3]]
  
  Sys.sleep(runif(1, min = 0.1, max = 0.2))

}

# Collapse list to dataframe 

new_df <- bind_rows(full_list) %>% distinct()

old_df <- readRDS("../data/temporary_manual_scrape/soukromnici_donation.rds")

full_df <- bind_rows(new_df, old_df) %>% distinct()


# USING A WHILE STATEMENT FOR KB with an undefined end

full_list <- list()
full_df <- tibble()
i <- 0
account_id <- "1153902720297"

while (load_more == TRUE) {
  
full_list[[as.character(i)]] <- fromJSON(content(GET(url = paste0("https://www.kb.cz/transparentsapi/transactions/", account_id, "?skip=", i)), as = "text"))[[3]]

load_more <- fromJSON(content(GET(url = paste0("https://www.kb.cz/transparentsapi/transactions/", account_id, "?skip=", i)), as = "text"))[[1]]
  
  i <- i + 50 
  
}

full_df <- bind_rows(full_list) %>% distinct()


# Save to RDS without modifications, save to CSV with slight modifications for better readability in Excel

file_path <- "../data/temporary_manual_scrape/soukromnici_donation.rds"
file_path_csv <- "../data/temporary_manual_scrape/csv/soukromnici_donation.csv"

saveRDS(full_df, file_path)

full_df <- readRDS(file_path)

full_df$date <- gsub(x = full_df$date, pattern = "&nbsp;", replacement = " ")

full_df$notes <- gsub(x = full_df$notes, pattern = "<br />", replacement = " - ")

fwrite(full_df, file_path_csv)

# CS API CALL

size <- 50
account_id <- "000000-0020091122"
sort_category <- "processingDate"
order <- "DESC"


new_df <- fromJSON(content(httr::VERB(
  verb = "GET", url = "https://api.csas.cz/webapi/api/v3/transparentAccounts/000000-0020091122/transactions",
  httr::add_headers(
    Connection = "keep-alive",
    Accept = "application/json, text/plain, */*",
    `WEB-API-key` = "08aef2f7-8b72-4ae1-831e-2155d81f46dd",
    `Accept-Language` = "cs",
    `User-Agent` = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
    `Sec-GPC` = "1", Origin = "https://www.csas.cz",
    `Sec-Fetch-Site` = "same-site",
    `Sec-Fetch-Mode` = "cors",
    `Sec-Fetch-Dest` = "empty",
    Referer = "https://www.csas.cz/"
  ),
  query = list(
    order = order,
    page = "0", 
    size = size,
    sort = sort_category
  )
), as = "text"), flatten = TRUE)[["transactions"]]



# FOR CS
old_df <- fromJSON(txt = "../data/temporary_manual_scrape/top09_donation.txt", flatten = TRUE)[["transactions"]]

full_df <- bind_rows(new_df, old_df) %>% distinct()

file_path <- "../data/temporary_manual_scrape/top09_donation.rds"
file_path_csv <- "../data/temporary_manual_scrape/csv/top09_donation.csv"

saveRDS(full_df, file_path)
fwrite(full_df, file_path_csv)


# FOR CSOB

new_df <- fromJSON("../data/temporary_manual_scrape/kscm_expense_2.txt", flatten = TRUE)

new_df <- new_df$accountedTransactions$accountedTransaction

new_df$baseInfo.accountingTypeId <- as.double(new_df$baseInfo.accountingTypeId)

new_df$baseInfo.transactionTypeCode <- as.double(new_df$baseInfo.transactionTypeCode)

new_df$baseInfo.transactionGroupCode <- as.logical(new_df$baseInfo.transactionGroupCode)

full_df <- bind_rows(new_df, old_df) %>% distinct()

file_path <- "../data/temporary_manual_scrape/kscm_expense.rds"
file_path_csv <- "../data/temporary_manual_scrape/csv/kscm_expense.csv"

saveRDS(full_df, file_path)

fwrite(full_df, file_path_csv)


```

