# Automated election accounts scraping with GitHub Actions

name: Transparent Accounts Scrape with Docker Image

# Controls when the action will run.
on:
  schedule:
    - cron:  '30 4 * * *'
  push:
    branches: master
    
jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: rocker/tidyverse:latest

    # Load repo and run the scraping script
    steps:
    - uses: actions/checkout@v2
    - name: Compile bank accounts list
      run: Rscript 00_save_bank_accounts.R
    - name: Scrape FIO bank accounts
      run: Rscript 01_scrape_fio_accounts.R
    - name: Create summary tables
      run: Rscript 02_create_summary_tables.R
    - name: Install Flexdashboard package
      run: Rscript -e "install.packages('flexdashboard')"
    - name: Update Dashboard for GitHub Pages  
      run: Rscript -e "rmarkdown::render('index.Rmd')"
    
 # Add new files in specified folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add data/* index.html
        git commit -am "GH Action $(date)"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
