# Automated election accounts scraping with GitHub Actions

name: transparent_accounts_scrape_with_docker

# Controls when the action will run.
on:
  schedule:
    - cron:  '30 4 * * *'
  push:
    branches: master
    
jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: rocker/tidyverse

    # Load repo and run the script
    steps:
    - uses: actions/checkout@v2
    - name: Docker Test
      run: Rscript docker_test.R
      
 # Add new files in specified folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add ucty_komplet/*
        git commit -am "GH Action $(date)"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
