# Automated election accounts scraping with GitHub Actions

name: Transparent Accounts Scrape with R-Lib

# Controls when the action will run.
on:
  schedule:
    - cron:  '30 4 * * *'
  push:
    branches: master
    
jobs: 
  autoscrape:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1

    # Set-up R
    - name: Install packages
      run: |
        Rscript -e 'install.packages(c("dplyr", "rvest", "readr"))'
    # Run R script
    - name: Scrape
      run: Rscript fio_scraping_script.R
      
 # Add new files in specified folder, commit along with other modified files, push
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add ucty_komplet/*
        git commit -am "GH Action $(date)"
        git push origin master
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
